// Cardapio oficial do Mangiare Ristorante. FONTE UNICA: site, link da bio e delivery leem daqui.
// Precos do PDF oficial. p:null = valor a combinar (nao entra em total automatico).
// entrega:false = servido SOMENTE no restaurante, nao aparece no delivery.
// Para tirar um prato da entrega, troque entrega:true por entrega:false na linha dele.
window.MANGIARE_CARDAPIO = {
  atualizado: "2026-07-29",
  categorias: [
    {
      cat: "Entradas",
      foto: "SABOR.webp",
      itens: [
        { n: "Burrata Tartufada", d: "Com tomates confitados e torradas italianas.", p: 108, entrega: true },
        { n: "Brie Flambado", d: "Com Cointreau, mel de frutas trufado e torradas.", p: 108, entrega: true },
        { n: "Couvert", d: "1/2 burrata com tomates coquetel, shitake, shimeji, cogumelos e azeitonas pretas confitadas, com torradas italianas.", p: 79, entrega: true },
        { n: "Camarão Alho e Óleo", d: "", p: 189, entrega: true },
        { n: "Burrata do Chef com Camarões", d: "", p: 169, entrega: true },
        { n: "Filé Aperitivo", d: "Com molho gorgonzola e torradas. Opções: madeira, acebolado, gorgonzola, funghi.", p: 129, entrega: true },
        { n: "Burrata do Chef", d: "", p: 98, entrega: true },
        { n: "Quarteto de Formaggio", d: "Gorgonzola, brie, parmesão e provolone.", p: 89, entrega: true },
        { n: "Bolinho de Bacalhau", d: "", p: 69, entrega: true },
        { n: "Carpaccio", d: "", p: 59, entrega: true },
        { n: "Bolinho de Arroz com Queijo", d: "", p: 55, entrega: true },
        { n: "Pastel de Carne e Queijo", d: "", p: 55, entrega: true },
        { n: "Batata Frita", d: "", p: 38, entrega: true },
      ],
    },
    {
      cat: "Saladas",
      foto: "SIMPLES.webp",
      itens: [
        { n: "Salada Caprese com Burrata", d: "", p: 89, entrega: true },
        { n: "Salada Del Capo", d: "", p: 79, entrega: true },
        { n: "Salada de Palmito com Tomate Coquetel", d: "", p: 59, entrega: true },
        { n: "Salada Caesars", d: "", p: 49, entrega: true },
      ],
    },
    {
      cat: "Bruschetas",
      foto: "SABOREAR.webp",
      itens: [
        { n: "Bruschetta Brie, Cogumelos e Parma", d: "", p: 69, entrega: true },
        { n: "Bruschetta de Gorgonzola com Parma", d: "", p: 69, entrega: true },
        { n: "Bruschetta de Queijo Brie com Tâmaras e Mel", d: "", p: 59, entrega: true },
        { n: "Bruschetta de Gorgonzola com Mel e Amêndoas", d: "", p: 48, entrega: true },
        { n: "Bruschetta Tradicional", d: "", p: 42, entrega: true },
      ],
    },
    {
      cat: "Risotos",
      foto: "PRATO.webp",
      itens: [
        { n: "Risoto de Camarão com Tomate e Brócolis", d: "", p: 159, entrega: true },
        { n: "Risoto de Camarão com Damasco e Queijo Brie", d: "", p: 159, entrega: true },
        { n: "Risoto Frutos do Mar", d: "", p: 129, entrega: true },
        { n: "Risoto de Filé com Funghi", d: "", p: 79, entrega: true },
        { n: "Risoto de Filé com 3 Queijos", d: "", p: 79, entrega: true },
        { n: "Risoto de Filé com Alho Poró", d: "", p: 79, entrega: true },
        { n: "Risoto de Salmão com Damasco", d: "", p: 79, entrega: true },
        { n: "Risoto de Salmão com Alho Poró", d: "", p: 79, entrega: true },
        { n: "Salmão com Alho-poró", d: "", p: 79, entrega: true },
        { n: "Risoto Gorgonzola, Pera e Nozes", d: "", p: 79, entrega: true },
        { n: "Risoto Vegetariano", d: "Shimeji, shitake, legumes e parmesão.", p: 79, entrega: true },
        { n: "Risoto Vegano", d: "Shimeji, shitake e legumes.", p: 79, entrega: true },
      ],
    },
    {
      cat: "Massas",
      foto: "COMIDA.webp",
      itens: [
        { n: "Fetuccine ao Champagne com Brie e Camarões Trufado", d: "", p: 159, entrega: true },
        { n: "Fetuccine Alfredo com Camarão", d: "", p: 159, entrega: true },
        { n: "Penne ao Limone com Camarão", d: "", p: 159, entrega: true },
        { n: "Spaguetti com Camarão e Tomate Fresco", d: "", p: 139, entrega: true },
        { n: "Spaghetti Frutos do Mar", d: "", p: 129, entrega: true },
        { n: "Ravioli de Muçarela com Molho Tomate Fresco", d: "", p: 79, entrega: true },
        { n: "Spaguetti Carbonara", d: "", p: 55, entrega: true },
        { n: "Gnocchi a Bolognesa", d: "", p: 55, entrega: true },
        { n: "Gnocchi 3 Queijos", d: "", p: 55, entrega: true },
        { n: "Fetuccine Matriciana", d: "", p: 53, entrega: true },
        { n: "Spaguetti a Putanesca", d: "", p: 53, entrega: true },
        { n: "Spaghetti Alho e Óleo com Bacon", d: "", p: 49, entrega: true },
        { n: "Spaguetti Bolognesa", d: "", p: 49, entrega: true },
        { n: "Penne Arrabiatta", d: "", p: 49, entrega: true },
      ],
    },
    {
      cat: "Peixes",
      foto: "ENCANTA.webp",
      itens: [
        { n: "Abadejo Saad", d: "Grelhado com pesto de ervas, arroz de polvo e camarões grelhados.", p: 169, entrega: true },
        { n: "Abadejo a Bella Donna", d: "Grelhado com molho de limão e alcaparras e camarão, arroz branco e legumes.", p: 146, entrega: true },
        { n: "Salmão com Risoto 3 Queijos Gratinado", d: "Com brie e mel.", p: 109, entrega: true },
        { n: "Salmão com Trio de Cogumelos", d: "Grelhado com trio de cogumelos e risoto negro com amêndoas.", p: 109, entrega: true },
        { n: "Salmão Maracujá", d: "Grelhado com molho maracujá e risoto de amêndoas.", p: 109, entrega: true },
        { n: "Tilápia ao Pesto com Risoto de Limão", d: "", p: 79, entrega: true },
        { n: "Tilápia Maracujá", d: "Grelhada ao molho maracujá com risoto de parmesão.", p: 79, entrega: true },
      ],
    },
    {
      cat: "Bacalhau",
      foto: "EXECUTIVO.webp",
      nota: "Cardápio especial · escolha o preparo + acompanhamento · R$ 179",
      itens: [
        { n: "Bacalhau Portuguesa", d: "Batata, alho, cebola, pimentão, azeitonas, ovo cozido.", p: 179, entrega: true },
        { n: "Bacalhau Gratinado", d: "Creme de parmesão, batata, azeitonas.", p: 179, entrega: true },
        { n: "Bacalhau Confit", d: "Batata, tomate cereja, pétalas de cebola roxa, palmito.", p: 179, entrega: true },
        { n: "Bacalhau Veneto", d: "Grelhado ao alho e óleo, tomates confit e brócolis.", p: 179, entrega: true },
        { n: "Bacalhau J.O.", d: "Grelhado no azeite, azeitonas, cebola, tomate e brócolis.", p: 179, entrega: true },
      ],
    },
    {
      cat: "Frutos do Mar",
      foto: "CAMARAO1.webp",
      itens: [
        { n: "Camarão Saint Jacques", d: "Recheado com catupiry à milanesa e risoto de amêndoas.", p: 159, entrega: true },
        { n: "Camarão Trufado Pomodoro", d: "Grelhado com molho de tomate fresco e ervas e risoto trufado de parmesão.", p: 159, entrega: true },
        { n: "Camarão Nero Trufado", d: "Grelhado com ervas e risoto ao Nero de sépia.", p: 159, entrega: true },
        { n: "Camarão Provençal", d: "Camarão provençal com arroz de brócolis.", p: 159, entrega: true },
      ],
    },
    {
      cat: "Carnes",
      foto: "CARNES.webp",
      itens: [
        { n: "Filet Mangiare", d: "Filé com camarões e ervas, risoto defumado com bacon e cebola caramelizada.", p: 159, badge: "⭐ Da casa", entrega: true },
        { n: "Prime Rib ao Alho", d: "Com arroz biro biro e batata frita.", p: 159, entrega: true },
        { n: "Filé Du Chef", d: "Tournedor alto grelhado com bacon, creme de cebola trufada e risoto de cogumelos paris.", p: 109, entrega: true },
        { n: "Filé ao Brie com Trio de Cogumelos", d: "E risoto de amêndoas.", p: 109, entrega: true },
        { n: "Filé Chateaubriant", d: "Filé alto grelhado, molho madeira com cogumelos, palmito e ervilha e risoto de parmesão.", p: 109, entrega: true },
        { n: "Filet Mignon au Poivre Vert", d: "Ao molho de pimenta verde conserva com risoto de parmesão.", p: 99, entrega: true },
        { n: "Filet Mignon ao Gorgonzola e Damasco", d: "Molho gorgonzola, risoto de damasco.", p: 98, entrega: true },
        { n: "Filet Mignon ao Gorgonzola e Palmito", d: "Molho gorgonzola, risoto de palmito.", p: 98, entrega: true },
        { n: "Filet Mignon Ilha di Capri", d: "Molho de 3 queijos, uva passas e amêndoas, arroz ao próprio molho.", p: 98, entrega: true },
        { n: "Filet Mignon a Parmeggiana", d: "À milanesa, molho de tomates, muçarela, presunto e fetuccine alfredo.", p: 98, entrega: true },
        { n: "Filet Mignon Trufado", d: "Ao molho de funghi com fetuccine trufado.", p: 98, entrega: true },
        { n: "Filé ao Molho de Mostarda Dijon", d: "Com risoto 3 queijos e alho poró.", p: 98, entrega: true },
        { n: "Beef Ancho ao Funghi", d: "Grelhado ao molho madeira com risoto de funghi.", p: 89, entrega: true },
        { n: "Beef Ancho Alfredo", d: "Grelhado ao molho madeira com fetuccine alfredo.", p: 89, entrega: true },
        { n: "Beef Ancho Bacon", d: "Molho madeira com risoto de bacon e cebola caramelizada.", p: 89, entrega: true },
        { n: "Beef Ancho Biro Biro", d: "Molho madeira com arroz biro biro e batata chips.", p: 89, entrega: true },
        { n: "Beef Ancho com Risoto de Gorgonzola", d: "Molho madeira e risoto de gorgonzola.", p: 89, entrega: true },
        { n: "Entrecote Café Paris", d: "Com molho de mostarda dijon à l'ancienne, batata frita.", p: 89, entrega: true },
      ],
    },
    {
      cat: "Cordeiro",
      foto: "JANTAR.webp",
      nota: "Todos R$ 189",
      itens: [
        { n: "Carré de Cordeiro J.G.", d: "Grelhado ao molho de ervas com vinho tinto, spaguetti com tomate fresco.", p: 189, entrega: true },
        { n: "Carré de Cordeiro Amabile", d: "Molho de vinho tinto e ervas, risoto zeferano.", p: 189, entrega: true },
        { n: "Carré de Cordeiro Tartufado", d: "Pesto de ervas, risoto de funghi tartufado.", p: 189, entrega: true },
        { n: "Carré de Cordeiro Mamma Mia", d: "Molho de vinho trufado, fetuccine alho e óleo.", p: 189, entrega: true },
      ],
    },
    {
      cat: "Kids",
      foto: "MOMENTOS.webp",
      itens: [
        { n: "Prato Kids", d: "", p: 59, entrega: true },
      ],
    },
    {
      cat: "Sobremesas",
      foto: "CELEBRE.webp",
      soNoSalao: true, motivo: "Servido somente no restaurante",
      itens: [
        { n: "Petit Gâteau com Sorvete", d: "", p: 31, entrega: false },
        { n: "Brownie com Sorvete de Creme e Calda de Chocolate", d: "", p: 31, entrega: false },
        { n: "Taça Mangiare", d: "Sorvete creme, creme de goiabada cascão e chantili de coco.", p: 31, entrega: false },
        { n: "Creme de Papaia", d: "", p: 28, entrega: false },
        { n: "Pudim de Leite Condensado", d: "", p: 19, entrega: false },
        { n: "Café Expresso", d: "", p: 9, entrega: false },
      ],
    },
    {
      cat: "Bebidas",
      foto: "VINHO.webp",
      nota: "Valores confirmados no WhatsApp / no local",
      soNoSalao: true, motivo: "Valores combinados no WhatsApp ou no local",
      itens: [
        { n: "Carta de Vinhos & Espumantes", d: "Peça a sugestão do sommelier para harmonizar.", p: null, entrega: false },
        { n: "Drinks & Coquetéis", d: "Aperol Spritz, Negroni, Bellini, Prosecco e autorais.", p: null, entrega: false },
        { n: "Refrigerante / Água / Suco", d: "", p: null, entrega: false },
      ],
    },
  ],
};
